FROM node:19-alpine as build-stage
WORKDIR /app
COPY . .
RUN npm ci --silent
RUN npm run build

FROM nginx:1.23-alpine
COPY --from=build-stage /app/build/ /usr/share/nginx/html
COPY --from=build-stage /app/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]